# Site setings
name: 'flicstar'
description: 'flicstar is a technical communicator, writing and editing online content with a technical focus.'
meta_description: 'flicstar is a technical communicator, writing and editing online content with a technical focus.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://flicstar.github.io/
disqus: 
mailchimp_url: 
title_image: 'assets/images/title_image.jpg'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics:


# Author
author:
  name: 'Felicity Brand'
  image: 'authorimage.png'
  greetings: "Felicity Brand - flicstar"
  description: "I'm a technical writer and editor. I am passionate about open source and I’m based in Melbourne, Australia."
  bio: 'Felicity Brand (aka flicstar) creates and edits a variety of technical content and loves to speak about the craft of writing and editing for technical audiences. She is passionate about open source, and is based in Melbourne, Australia'

# Contact form setings
email: flicstar@gmail.com
contact_page_description:
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'flicstar_'
facebook:
github: 'flicstar'
gitlab: 'flicstar'
codepen:
dribbble:
medium:
instagram: 'flicstaryarnstar'
pinterest:
linkedin: 'felicitybrand'
producthunt:

# Navigation (example text: Style Guide  url: /style-guide/)
navigation:
  - text: About
    url: /about
  - text: Need a review?
    url: /peer-review
  - text: Writing
    url: /writing/writing

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
